GROUND_HEALTH: 100
AIR_HEALTH: 100
CUAS_HEALTH: 100

NOMINAL_GROUND_DAMAGE: 100
NOMINAL_AIR_DAMAGE: 100
NOMINAL_CUAS_DAMAGE: 100

GROUND_SPEED: 3
AIR_SPEED: 20

GROUND_OBS_RADIUS: 30
AIR_OBS_RADIUS: 100

GROUND_FLAG_CAPTURE: 0.2
AIR_FLAG_CAPTURE: 0.1
FLAG_CAPTURE_RADIUS: 10

PROB_ENGAGE_SUCCESS: 0.95
PROB_COMM_SUCCESS: 0.8

MAX_SLOPE: 0.035


ELIMINATE_REWARD: 3.0
FLAG_HOLD_REWARD: 0.3
FLAG_CAPTURE_REWARD: 1.0

N_GROUND_AGENTS: 10
N_AIR_AGENTS: 10
N_FLAGS: 5

MAX_EVENTS: 10
TTL: 20