GROUND_HEALTH: 100
AIR_HEALTH: 100
CUAS_HEALTH: 100

NOMINAL_GROUND_DAMAGE: 100
NOMINAL_AIR_DAMAGE: 100
NOMINAL_CUAS_DAMAGE: 100

GROUND_SPEED: 3
AIR_SPEED: 20

GROUND_OBS_RADIUS: 30
AIR_OBS_RADIUS: 100

PROB_ENGAGE_SUCCESS: 0.95


MAX_SLOPE: 0.2